/**
 * Shared Juliet per-testcase Makefile generator — used by ingest.ts (fresh ingest)
 * and repair-makefiles.ts (regenerate in-place over an already-materialized corpus,
 * without needing the original NIST source tree).
 *
 * Builds BOTH paths (good + bad), instrumented with LeakSanitizer, into one `a.out`
 * so a single instrumented run exercises every function (a clean good* function is
 * genuinely `exercised_clean`, not merely un-tested).
 *
 * Some Juliet C++ variants (`destructor`, `virtual`, …) split bad/good into SEPARATE
 * files that EACH carry their own `#ifdef INCLUDEMAIN int main(...)` — linking both
 * into one binary is a duplicate-`main` error. When more than one file in a testcase
 * independently defines `main`, only the `_bad` file's main is compiled in (`DEFS`);
 * the rest build without it (`DEFS_NOMAIN`) — their functions still link into the
 * binary, just unreached from `main`, so `dynamicCoverage` honestly reports
 * `not_exercised` for that side instead of the whole case failing to build.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const OWN_MAIN_RE = /#ifdef\s+INCLUDEMAIN[\s\S]*?\bint\s+main\s*\(/;

/** Which of a testcase's own .c/.cpp files (not shared support files) define a guarded main(). */
export function ownMainFiles(caseDir: string, testcaseFiles: string[]): string[] {
  return testcaseFiles.filter((f) => {
    try {
      return OWN_MAIN_RE.test(readFileSync(join(caseDir, f), 'utf-8'));
    } catch {
      return false;
    }
  });
}

export function generateJulietMakefile(caseDir: string, testcaseFiles: string[]): string {
  const hasCpp = testcaseFiles.some((f) => /\.cpp$/i.test(f));
  const mains = ownMainFiles(caseDir, testcaseFiles);
  const mainFile = mains.length > 1 ? (mains.find((f) => /_bad\./.test(f)) ?? mains[0]) : mains[0];
  const secondaryMains = mains.length > 1 ? mains.filter((f) => f !== mainFile) : [];

  const overrides = secondaryMains
    .map((f) => {
      const obj = f.replace(/\.(c|cpp)$/, '.o');
      const compiler = f.endsWith('.cpp') ? '$(CXX)' : '$(CC)';
      return `${obj}: ${f}\n\t${compiler} $(SAN) $(DEFS_NOMAIN) $(INC) -c $< -o $@`;
    })
    .join('\n\n');

  return [
    '# Auto-generated by scripts/juliet/ingest.ts — standalone Juliet testcase.',
    '# Builds BOTH paths (good + bad), instrumented with LeakSanitizer.',
    'CC ?= clang',
    'CXX ?= clang++',
    'SAN ?= -fsanitize=leak -fno-omit-frame-pointer -g -O0',
    'DEFS ?= -DINCLUDEMAIN',
    'DEFS_NOMAIN ?=',
    'INC ?= -I.',
    'CSRC := $(wildcard *.c)',
    'CPPSRC := $(wildcard *.cpp)',
    'COBJ := $(CSRC:.c=.o)',
    'CPPOBJ := $(CPPSRC:.cpp=.o)',
    `LINK := ${hasCpp ? '$(CXX)' : '$(CC)'}`,
    '',
    'a.out: $(COBJ) $(CPPOBJ)',
    '\t$(LINK) $(SAN) $(COBJ) $(CPPOBJ) -o a.out',
    '',
    '%.o: %.c',
    '\t$(CC) $(SAN) $(DEFS) $(INC) -c $< -o $@',
    '',
    '%.o: %.cpp',
    '\t$(CXX) $(SAN) $(DEFS) $(INC) -c $< -o $@',
    '',
    ...(overrides ? [overrides, ''] : []),
    'run: a.out',
    '\tLSAN_OPTIONS=verbosity=1 ./a.out || true',
    '',
    'clean:',
    '\trm -f *.o a.out',
    '',
    '.PHONY: run clean',
    '',
  ].join('\n');
}

/** The dynamic stage's build command: `clean` first so a flag change (e.g. LSan → ASan
 * across two invocations of the same materialized case dir) can never leave a stale
 * `.o` linked against a mismatched sanitizer runtime — that mismatch is exactly the
 * "undefined reference to `__asan_*`" class of link error make's mtime-only staleness
 * tracking cannot catch on its own. */
export const JULIET_BUILD_COMMAND = 'make clean && make CC=clang CXX=clang++';
